services:
  mongo1:
    container_name: mongo-mongo-1
    extends:
      file: ./docker-compose-mongo.yml
      service: mongo
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0", "--port",  "27017"]

  mongo2:
    container_name: mongo-mongo-2
    extends:
      file: ./docker-compose-mongo.yml
      service: mongo
    volumes:
      - mongo2_data:/data/db
      - mongo2_config:/data/configdb
    ports:
    - 27018:27018
    command: ["mongod", "--replSet", "rs0", "--port",  "27018"]

  mongo3:
    container_name: mongo-mongo-3
    extends:
      file: ./docker-compose-mongo.yml
      service: mongo
    volumes:
      - mongo3_data:/data/db
      - mongo3_config:/data/configdb
    ports:
      - 27019:27019
    command: ["mongod", "--replSet", "rs0", "--port",  "27019"]

volumes:
  mongo_data:
  mongo_config:
  mongo2_data:
  mongo2_config:
  mongo3_data:
  mongo3_config:
