version: '3.8'

services:
  mongo:
    image: mongo:7.0.8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    expose:
      - 27017
    networks:
      - mongo_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  mongo_data:
  mongo_config:

networks:
  mongo_net:
    driver: bridge
