version: '3.8'

name: mongo

services:
  mongo:
    extends:
      file: ./docker-compose-mongo.yml
      service: mongo
    ports:
      - 27017:27017

volumes:
  mongo_data:
  mongo_config:

networks:
  mongo_net:
    driver: bridge
